name: "Generate missing routes"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "**" ]

jobs:
  generate:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run start
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git diff-index --quiet HEAD || git commit -m "Update state"
      - run: git push
